import "server-only";

import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { createSupabaseAdminClient } from "@/lib/supabase/server";
import { downloadEnvelopePdf, uploadSignedEnvelopePdf } from "@/lib/envelopes/storage";
import type { EnvelopeWithDetails } from "@/lib/envelopes/types";

const INK = rgb(0.1, 0.1, 0.12);
const MUTED = rgb(0.4, 0.4, 0.44);

function fmt(value: string | null | undefined) {
  if (!value) return "—";
  const d = new Date(value);
  return Number.isNaN(d.getTime()) ? value : d.toLocaleString("en-US");
}

// Appends a signing audit page to the completed envelope's signed PDF — the
// "certificate of completion" that records who signed, when, and from where.
export async function appendCompletionCertificate(envelope: EnvelopeWithDetails): Promise<void> {
  const signedPath = envelope.document?.signed_storage_path;
  if (!signedPath || !envelope.document) return;

  const supabase = createSupabaseAdminClient();
  const { data: sigRows } = await supabase
    .from("signatures")
    .select("signer_id, ip_address")
    .eq("envelope_id", envelope.id);
  const ipBySigner = new Map<string, string>();
  for (const row of (sigRows ?? []) as Array<{ signer_id: string; ip_address: string | null }>) {
    if (row.ip_address && !ipBySigner.has(row.signer_id)) ipBySigner.set(row.signer_id, row.ip_address);
  }

  const pdfBytes = await downloadEnvelopePdf(signedPath);
  const pdf = await PDFDocument.load(pdfBytes);
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);

  const page = pdf.addPage([612, 792]);
  const { width, height } = page.getSize();
  const left = 54;
  let y = height - 64;

  const line = (text: string, opts: { size?: number; font?: typeof font; color?: typeof INK; gap?: number } = {}) => {
    const size = opts.size ?? 10;
    page.drawText(text, { x: left, y, size, font: opts.font ?? font, color: opts.color ?? INK, maxWidth: width - left * 2 });
    y -= opts.gap ?? size + 6;
  };

  line("Certificate of Completion", { size: 20, font: bold, gap: 30 });
  line(`Envelope: ${envelope.title}`, { size: 12, font: bold, gap: 18 });
  line(`Envelope ID: ${envelope.id}`, { color: MUTED });
  line(`Status: ${envelope.status}`, { color: MUTED });
  line(`Completed: ${fmt(envelope.completed_at)}`, { color: MUTED });
  line(`Signing order: ${envelope.signing_order}`, { color: MUTED, gap: 26 });

  line("Signers", { size: 13, font: bold, gap: 20 });

  // ponytail: one-page certificate. Ceiling ~10 signers before running off the page;
  // upgrade path is to start a fresh page when y < margin and redirect `line` to it.
  const ordered = [...envelope.signers].sort((a, b) => a.order_index - b.order_index);
  for (const signer of ordered) {
    if (y < 110) break;
    line(`${signer.name}  ·  ${signer.assigned_role}`, { size: 11, font: bold, gap: 15 });
    line(`Email: ${signer.user_email}`, { color: MUTED });
    line(`Status: ${signer.status}`, { color: MUTED });
    line(`Viewed: ${fmt(signer.viewed_at)}    Signed: ${fmt(signer.signed_at)}`, { color: MUTED });
    line(`IP address: ${ipBySigner.get(signer.id) ?? "—"}`, { color: MUTED, gap: 20 });
  }

  line("This certificate is generated by SignDoc as a record of the electronic signing process.", {
    size: 8,
    color: MUTED,
    gap: 12,
  });

  const bytes = new Uint8Array(await pdf.save());
  const newPath = await uploadSignedEnvelopePdf(envelope.id, bytes);
  const { error } = await supabase
    .from("envelope_documents")
    .update({ signed_storage_path: newPath })
    .eq("id", envelope.document.id);
  if (error) throw new Error(`Failed to record certificate revision: ${error.message}`);
}
